services:
  phql-dev-8.1:
    container_name: phql-dev-8.1
    hostname: phql-dev-81
    build:
      dockerfile: resources/docker/develop/Dockerfile
      args:
        PHP_VERSION: 8.1
    working_dir: /app
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  phql-dev-8.2:
    container_name: phql-dev-8.2
    hostname: phql-dev-82
    build:
      dockerfile: resources/docker/develop/Dockerfile
      args:
        PHP_VERSION: 8.2
    working_dir: /app
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  phql-dev-8.3:
    container_name: phql-dev-8.3
    hostname: phql-dev-83
    build:
      dockerfile: resources/docker/develop/Dockerfile
      args:
        PHP_VERSION: 8.3
    working_dir: /app
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  phql-dev-8.4:
    container_name: phql-dev-8.4
    hostname: phql-dev-84
    build:
      dockerfile: resources/docker/develop/Dockerfile
      args:
        PHP_VERSION: 8.4
    working_dir: /app
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  phql-dev-8.5:
    container_name: phql-dev-8.5
    hostname: phql-dev-85
    build:
      dockerfile: resources/docker/develop/Dockerfile
      args:
        PHP_VERSION: 8.5
    working_dir: /app
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
